services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 myproject.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - ./session_name.session:/app/session_name.session
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  static_volume: