# Generated by Django 5.1.1 on 2025-05-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('posts_fetched', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.telegramchannel')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('link', models.URLField(max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('forwards', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('er_post', models.FloatField(default=0.0)),
                ('er_view', models.FloatField(default=0.0)),
                ('vr_post', models.FloatField(default=0.0)),
                ('tr', models.FloatField(default=0.0)),
                ('post_type', models.CharField(default='text', max_length=50)),
                ('subscribers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.telegramchannel')),
            ],
            options={
                'unique_together': {('channel', 'post_id')},
            },
        ),
    ]
