# Generated by Django 5.1.1 on 2025-05-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('link', models.URLField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('forwards', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('er_post', models.FloatField(default=0.0)),
                ('er_view', models.FloatField(default=0.0)),
                ('vr_post', models.FloatField(default=0.0)),
                ('post_type', models.CharField(default='text', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.channel')),
            ],
            options={
                'unique_together': {('channel', 'post_id')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('forwards', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoticon', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_items', to='myapp.post')),
            ],
        ),
    ]
