# Generated by Django 5.1.1 on 2025-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
