# Generated by Django 5.1.1 on 2025-05-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_telegramchannel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchannel',
            name='avatar',
        ),
    ]
