# Generated by Django 5.1.1 on 2025-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_telegramchannel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
